export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const PREVIOUS_QUESTION = 'PREVIOUS_QUESTION';
export const NEXT_QUESTION = 'NEXT_QUESTION';

export const TRY_RETRIEVE_AUTH_DATA = 'TRY_RETRIEVE_AUTH_DATA';
export const FETCH_AUTH_DATA = 'FETCH_AUTH_DATA';
export const FETCH_AUTH_DATA_SUCCEEDED = 'FETCH_AUTH_DATA_SUCCEEDED';
export const FETCH_AUTH_DATA_FAILED = 'FETCH_AUTH_DATA_FAILED';
export const EXPIRE_AUTH_DATA = 'EXPIRE_AUTH_DATA';