export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const PREVIOUS_QUESTION = 'PREVIOUS_QUESTION';
export const NEXT_QUESTION = 'NEXT_QUESTION';
