export const PREVIOUS_QUESTION = 'PREVIOUS_QUESTION';
export const NEXT_QUESTION = 'NEXT_QUESTION';

export const LOAD_USER = 'LOAD_USER';
export const EXPIRE_AUTH_DATA = 'EXPIRE_AUTH_DATA';

export const NAVIGATE = 'NAVIGATE';